package com.selinuxtoolbox.core.domain.usecase

import com.selinuxtoolbox.core.domain.analyzer.CilGenerator
import com.selinuxtoolbox.core.domain.analyzer.OutputFileInstruction
import com.selinuxtoolbox.core.domain.path.PathResolver
import com.selinuxtoolbox.core.domain.repository.BackupOrchestrator
import com.selinuxtoolbox.core.domain.repository.BackupResult
import com.selinuxtoolbox.core.model.ActiveMode
import com.selinuxtoolbox.core.model.ActionType
import com.selinuxtoolbox.core.model.DenialGroup
import com.selinuxtoolbox.core.model.FixSuggestion
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import javax.inject.Inject

sealed class ApplyFixResult {
    data class Success(val outputFolderPath: String, val rulesWritten: Int) : ApplyFixResult()
    data class Failure(val reason: String) : ApplyFixResult()
}

class ApplyDenialFixesUseCase @Inject constructor(
    private val pathResolver: PathResolver,
    private val backupOrchestrator: BackupOrchestrator
) {
    // acceptedGroups: only the DenialGroups the user accepted in the UI
    suspend operator fun invoke(
        projectId: Long,
        workPath: String,
        aospPath: String,
        mode: ActiveMode,
        acceptedGroups: List<DenialGroup>
    ): ApplyFixResult = withContext(Dispatchers.IO) {
        try {
            val outDir = pathResolver.outputDir(workPath, "avc_fix")
            outDir.mkdirs()

            // Collect all SimpleAllow suggestions from accepted groups
            val allowRules = acceptedGroups.flatMap { group ->
                group.suggestions.filterIsInstance<FixSuggestion.SimpleAllow>()
            }

            if (allowRules.isEmpty()) {
                return@withContext ApplyFixResult.Failure("No allow rules to apply")
            }

            val vendorCilFile = File(outDir, "vendor_sepolicy.cil")

            // Use BackupOrchestrator so the action is logged + undoable
            val backupResult = backupOrchestrator.executeWithBackup(
                projectId      = projectId,
                actionType     = ActionType.DENIAL_RULE_ADD,
                description    = "AVC denial fix: ${allowRules.size} allow rules from log analysis",
                projectOutputDir = workPath,
                filesToModify  = listOf(vendorCilFile),
                metadata       = mapOf(
                    "output_folder" to outDir.absolutePath,
                    "rules_count"   to allowRules.size.toString(),
                    "log_source"    to "imported_log"
                )
            ) {
                // Build the CIL file content
                val content = buildString {
                    appendLine("; ── AVC Denial Fix ─────────────────────────────────────────────")
                    appendLine("; Generated by SELinux Toolbox — APPEND to vendor_sepolicy.cil")
                    appendLine("; ${java.util.Date()}")
                    appendLine("; ${allowRules.size} allow rules from ${acceptedGroups.size} denial groups")
                    appendLine()

                    acceptedGroups.forEach { group ->
                        val groupRules = group.suggestions.filterIsInstance<FixSuggestion.SimpleAllow>()
                        if (groupRules.isNotEmpty()) {
                            appendLine("; ${group.sourceDomain} → ${group.targetType} (${group.objectClass})")
                            groupRules.forEach { fix -> appendLine(fix.cilRule) }
                            appendLine()
                        }
                    }
                }
                mapOf(vendorCilFile to content)
            }

            when (backupResult) {
                is BackupResult.Failure -> ApplyFixResult.Failure(backupResult.reason)
                is BackupResult.Success -> {
                    // Write INSTRUCTIONS.txt
                    val instructions = CilGenerator.instructionsTxt(
                        operation   = "AVC Denial Fix",
                        outputFiles = listOf(
                            OutputFileInstruction(
                                fileName    = "vendor_sepolicy.cil",
                                destination = "vendor/etc/selinux/vendor_sepolicy.cil",
                                action      = "APPEND — add these lines to the end of vendor_sepolicy.cil",
                                notes       = listOf(
                                    "Do NOT replace the full file",
                                    "Run secilc dry-run (Validator feature) after applying"
                                )
                            )
                        )
                    )
                    File(outDir, "INSTRUCTIONS.txt").writeText(instructions)

                    ApplyFixResult.Success(
                        outputFolderPath = outDir.absolutePath,
                        rulesWritten     = allowRules.size
                    )
                }
            }
        } catch (e: Exception) {
            ApplyFixResult.Failure("Unexpected error: ${e.message}")
        }
    }
}
