package com.selinuxtoolbox.core.domain.usecase

import com.selinuxtoolbox.core.data.util.FileUtil
import com.selinuxtoolbox.core.domain.analyzer.CilGenerator
import com.selinuxtoolbox.core.domain.analyzer.OutputFileInstruction
import com.selinuxtoolbox.core.domain.analyzer.SafetyConfig
import com.selinuxtoolbox.core.domain.analyzer.TypeSafety
import com.selinuxtoolbox.core.domain.parser.ContextFileParser
import com.selinuxtoolbox.core.domain.path.PathResolver
import com.selinuxtoolbox.core.domain.path.PolicyPartition
import com.selinuxtoolbox.core.model.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import javax.inject.Inject
import javax.inject.Singleton

// FIXED: Using ContextFileType enum constants instead of string literals
@Singleton
class GenerateMissingContextsUseCase @Inject constructor(
    private val fullComparisonUseCase: FullComparisonUseCase,
    private val pathResolver: PathResolver,
    private val contextParser: ContextFileParser
) {

    suspend operator fun invoke(
        oemPath: String,
        aospPath: String,
        workPath: String,
        acceptedTypes: Set<String>
    ): Result<File> = withContext(Dispatchers.IO) {
        try {
            val comparisonResult = fullComparisonUseCase(oemPath, aospPath, workPath)
            if (comparisonResult is FullComparisonResult.SetupError) {
                return@withContext Result.failure(Exception(comparisonResult.reason))
            }
            val report = (comparisonResult as FullComparisonResult.Success).report

            val missingEntries = report.missingContextEntries
                .filter { it.type in acceptedTypes }
                .filter { SafetyConfig.classify(it.type) != TypeSafety.UNSAFE }

            if (missingEntries.isEmpty()) {
                return@withContext Result.failure(Exception("No missing context entries to generate"))
            }

            val byPartition = missingEntries.groupBy { it.partition }

            val ts = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date())
            val outDir = File(workPath, "outputs/context_diff_$ts")
            outDir.mkdirs()

            val instructions = mutableListOf<OutputFileInstruction>()

            byPartition.forEach { (partitionName, entries) ->
                val partition = PolicyPartition.values().firstOrNull { it.dirName == partitionName }
                    ?: PolicyPartition.VENDOR

                val types = entries.map { it.type }.distinct()
                val cilSb = StringBuilder()
                val fcSb = StringBuilder()

                cilSb.appendLine("; Generated by SELinux Toolbox – Context Diff")
                cilSb.appendLine("; Missing types for ${partition.dirName}: ${types.size}")
                cilSb.appendLine()

                types.forEach { typeName ->
                    val entry = entries.first { it.type == typeName }
                    val fileType = entry.fileType
                    val cilBlock = when (fileType) {
                        ContextFileType.FILE, ContextFileType.SEAPP, ContextFileType.PROCESS ->
                            CilGenerator.fileType(typeName, partition)
                        ContextFileType.PROPERTY ->
                            CilGenerator.propertyType(typeName)
                        ContextFileType.SERVICE ->
                            CilGenerator.serviceType(typeName)
                        ContextFileType.HWSERVICE ->
                            CilGenerator.hwserviceType(typeName)
                        ContextFileType.VNDSERVICE ->
                            CilGenerator.serviceType(typeName)
                        else ->
                            CilGenerator.fileType(typeName, partition)
                    }
                    cilSb.append(cilBlock).append("\n")
                }

                entries.forEach { entry ->
                    fcSb.appendLine(entry.pattern + "    " + entry.context)
                }

                val cilFile = File(outDir, "${partition.dirName}_sepolicy.cil")
                cilFile.writeText(cilSb.toString())

                val firstEntryFileType = entries.first().fileType
                val contextFileName = when (firstEntryFileType) {
                    ContextFileType.FILE -> "${partition.dirName}_file_contexts"
                    ContextFileType.PROPERTY -> "${partition.dirName}_property_contexts"
                    ContextFileType.SERVICE -> "${partition.dirName}_service_contexts"
                    ContextFileType.HWSERVICE -> "${partition.dirName}_hwservice_contexts"
                    ContextFileType.VNDSERVICE -> "vndservice_contexts"
                    ContextFileType.SEAPP -> "${partition.dirName}_seapp_contexts"
                    else -> "${partition.dirName}_file_contexts"
                }
                val contextFile = File(outDir, contextFileName)
                contextFile.writeText(fcSb.toString())

                instructions.add(
                    OutputFileInstruction(
                        fileName = cilFile.name,
                        destination = "AOSP/${partition.dirName}/selinux/",
                        action = "NEW FILE (or APPEND to existing ${partition.dirName}_sepolicy.cil)",
                        notes = listOf("${types.size} type declarations")
                    )
                )
                instructions.add(
                    OutputFileInstruction(
                        fileName = contextFile.name,
                        destination = "AOSP/${partition.dirName}/selinux/",
                        action = "APPEND to existing ${contextFileName}",
                        notes = listOf("${entries.size} context entries")
                    )
                )
            }

            val instructionsTxt = File(outDir, "INSTRUCTIONS.txt")
            instructionsTxt.writeText(
                CilGenerator.instructionsTxt("Context Diff", instructions)
            )

            Result.success(outDir)
        } catch (e: Exception) {
            Result.failure(Exception("GenerateMissingContexts failed: ${e.message}", e))
        }
    }
}
